### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by ChenXuelinCXL** [czq142857/IM-NET#1]
Hi @czq142857 , the backup linke for IMAE&IMSVR data and pretrained weights seems incorrect, linking to the download of pointcloud_surface file, can you please help to check out if the link is correct:)?

Thanks!

**Comment by czq142857** [comment]
Thanks for pointing it out.
It seems I accidentally swapped "pointcloud_surface" and "IM-NET".
I have corrected it.

Best,
Zhiqin

**Comment by ChenXuelinCXL** [comment]
I finally downloaded the file from the IM-NET link, but it seems like there is no checkpoint under IMGAN/checkpoint...

**Comment by czq142857** [comment]
Please copy it from IMSVR. I did not train GAN so you can only get AE results with the provided weights.


Best,
Zhiqin



---Original---
