### ISSUE TITLE
How to get the required .binvox voxel model?

### ISSUE THREAD

**Issue by czsc123** [czq142857/IM-NET#10]
Hi Zhiqin,

Thanks for the great work.

I follow your suggestions in other issues that i normalize each shape so that the diagonal of its bounding box equals to unit  length.Then i use binvox.exe to voxelize the mesh to voxel. But i find the binvox.exe still rescale  and translate the bounding box into a unit cube. And i found the example .binvox voxel in your original sampling points directory has a unit length  diagonal .

if you use the binvox.exe to voxelize the mesh, could you please tell me the command that you use in terminal?
Or , if you use other voxelization tools or voxelization method, could you please share me or guild me how to voxelize the mesh ?

Best regards,
czsc

**Comment by czq142857** [comment]
1. use this command:
binvox -bb -0.5 -0.5 -0.5 0.5 0.5 0.5 -d 64 -e input.obj
"-bb" defines the bounding box.

2. The voxels in "samplechair" are normalized in the wrong way I think. They only serve as examples for testing the code.

Best,
Zhiqin

**Comment by czsc123** [comment]
It works, thank you!
