### ISSUE TITLE
Generating my image

### ISSUE THREAD

**Issue by hyunynim** [czq142857/IM-NET#11]
Hi, thank you for good code.

I want to know how can I generate my image using this code.
I think dataset "pixels" in "all_vox256_img_test.hdf5" is image. But I dont know how can I make dataset using my image.

Thank you

**Comment by czq142857** [comment]
Please check here:
https://github.com/czq142857/IM-NET/blob/master/point_sampling/3_gather_img.py

**Comment by czq142857** [comment]
If you only want to test on single images, run function *test_image* in *IMSVR/model.py*.

**Comment by hyunynim** [comment]
Thank you for answer!
