### ISSUE TITLE
Creating hdf5 files from .obj files

### ISSUE THREAD

**Issue by Komti13** [czq142857/IM-NET#19]
Hello i was trying to create my own hdf5 dataset to use for ucsgnet. i want to generate the file from an .obj file extension but i keep getting empty hdf5 files please some help . i followed all the given instructions in the repository

**Comment by czq142857** [comment]
This repo does not contain code or instructions to create hdf5 files from obj files. Did you use the code from somewhere else?

Anyway, please make sure your input data (the binary voxels) are not emply. If they are not empty, the output hdf5 files should not be empty.

**Comment by Komti13** [comment]
i am trying to run the files in point sampling folder to prepare my own data as an input for ucsgnet repository 
as input i used an obj file (mesh) but it doesent work

**Comment by czq142857** [comment]
Yes. You can read other issues for how to convert obj into binvox.

**Comment by Komti13** [comment]
okay thanks a lot for your help

**Comment by Komti13** [comment]
Excuse me i did the conversion to .binvox files but there this error in code of .mat files extension which i dont know for what it stand for 
![image](https://user-images.githubusercontent.com/59767842/168047677-4a93753e-1486-4d95-87e5-588bb9237372.png)
please tell me what are the .mat files that i should get avoid this error

**Comment by Komti13** [comment]
I tried to change the code and open the binvox file like following
![image](https://user-images.githubusercontent.com/59767842/168089031-8c0b1c8a-82e3-4e5d-881b-d7536c9a9c6a.png)
and i get this error 
![image](https://user-images.githubusercontent.com/59767842/168089176-fa193d02-c995-4992-8f5b-d4bf60914293.png)

**Comment by czq142857** [comment]
You only need to assign the voxel grid to voxel_model_256. So here's what you should do.

Replace the following
```
		#get voxel models
		try:
			voxel_model_mat = loadmat(name_list[idx][1])
		except:
			print("error in loading")
			exit(-1)
		
		
		
		voxel_model_b = voxel_model_mat['b'][:].astype(np.int32)
		voxel_model_bi = voxel_model_mat['bi'][:].astype(np.int32)-1
		voxel_model_256 = np.zeros([256,256,256],np.uint8)
		for i in range(16):
			for j in range(16):
				for k in range(16):
					voxel_model_256[i*16:i*16+16,j*16:j*16+16,k*16:k*16+16] = voxel_model_b[voxel_model_bi[i,j,k]]
		#add flip&transpose to convert coord from shapenet_v1 to shapenet_v2
		voxel_model_256 = np.flip(np.transpose(voxel_model_256, (2,1,0)),2)
```

with
```
		voxel_model_file = open(name_list[idx][1], 'rb')
		voxel_model_256 = binvox_rw.read_as_3d_array(voxel_model_file).data.astype(np.uint8)
		#you need to make absolutely sure that the top direction of your shape is j-positive direction in the voxels,
		#otherwise the z-carving code will not work properly. (z-carving ≈ floodfill to make the voxels solid inside)
		#you can adjust the direction of your voxels via np.flip and np.transpose.
```

**Comment by Komti13** [comment]
Thank you for your response it really helps, but unfortunately the error this time that the voxel is not of length 256. so it raise an error of index out of bounds
![image](https://user-images.githubusercontent.com/59767842/168176887-60754332-ced6-4b4c-8895-914bc339f3c9.png)
the object voxel_model_256 has a length of 64.

**Comment by czq142857** [comment]
So just prepare 256^3 voxels.

**Comment by Komti13** [comment]
Okay thank you for helping
