### ISSUE TITLE
Loss range

### ISSUE THREAD

**Issue by elamirloo** [czq142857/IM-NET#20]
Hi, in issue #17 you mentioned the loss 0.07 is not right and it indicates all zero values for the points. what is the expected range of loss from the beginning to the end of training in each phase (approximately)? -trying to debug my pipeline-

**Comment by czq142857** [comment]
Hi. You can refer to the losses reported in an issue of BAE-Net: https://github.com/czq142857/BAE-NET/issues/4.
But note that the losses of IM-NET should be much better than the losses of BAE-Net.
