### ISSUE TITLE
What does variable "b" and "bi" represent in .mat file of HSP 

### ISSUE THREAD

**Issue by bowensu123** [czq142857/IM-NET#21]
Dear Mr zhiqin,
   Appreciate your great work and released codes!
   Could you please help explain a little bit what variable "b" and "bi" represent in .mat file of HSP ? Thanks for your help!

Best,
Bowen

**Comment by czq142857** [comment]
I think b is a dictionary of 16^3 voxel patches, and bi is the indices to b. For example, GT_voxel[0:16,0:16,0:16] = b[bi[0,0,0]].

**Comment by bowensu123** [comment]
Dear Mr zhiqin,
  Thanks pretty much! Really appreciate it! Could you help explain a little bit  what the variable left_min, left_max,front_min,front_max these variables used for in the 2_gather_256vox_16_32_64.py?  Could you help explain a little bit about what  the the following codes is used for ? Thanks for your help!

![WeChate77823e74e397d769a086605d4f2e7e9](https://user-images.githubusercontent.com/64697240/206926575-df5757c2-ed48-4218-bf50-2b0a5566a1d3.png)
Best,
Bowen

**Comment by czq142857** [comment]
This code is a simple depth fusion. Only voxels that are invisible from top view (top_view), left view (left_min), right view (left_max), front view (front_min), and back view (front_max) classify as inside the shape.

**Comment by bowensu123** [comment]
Dear Mr zhiqin,

   Thanks for your help! 
    What does depth fusion mean? I run one .mat file and found this code does not change the variable voxel_model_256. Could you help figure out where I make something wrong.  Thanks pretty much!

Best,
Bowen

**Comment by czq142857** [comment]
Please search depth fusion on internet. It is not exactly depth fusion, so I would suggest you read the code carefully to figure it out. By the way, you don't have to understand this part of code. You can just use itm

**Comment by bowensu123** [comment]
Dear Mr zhiqin，
   Thanks pretty much for your help
Best,
Bowen
