### ISSUE TITLE
NameError IMAE

### ISSUE THREAD

**Issue by HeyamM** [czq142857/IM-NET#22]
![ErrorIM](https://user-images.githubusercontent.com/83015730/207981875-39d854be-b908-4267-a102-5f7c1746293b.jpg)
When I tried to implement your code for [IMGAN](https://github.com/czq142857/IM-NET/tree/master/IMGAN), I got an error (NameError for IMAE) as shown in the attached image. I have used the latest version of TensorFlow=2.0 and python=3.8, and Cuda=11.x, so if you could help me, please do so as soon as possible to fix this error because I'm a PhD student. I'm very interested in your work. Hopefully, I will get an answer very soon.

**Comment by czq142857** [comment]
It is not my duty to help you fix the bug. Please either use the provided code or debug by yourself.
