### ISSUE TITLE
Question about data resolution on 128^3

### ISSUE THREAD

**Issue by WayneCV** [czq142857/IM-NET#24]
Greets, I like your work. In your paper, you sampled points on $16^3, 32^3, 64^3, 128^3$. However, in your code about point_sampling, you provided all mentioned resolutions except $128^3$, and the commands about training also ignored $128^3$. Could you share the point sampling code on $128^3$ or explain why the commands about training stage (autoencoding) do not use $128^3$? Thanks in advance.

**Comment by czq142857** [comment]
This repo is designed to train a single model on 13 categories, so 128 resolution is probably too complex for the network to learn.

You can find 128 resolution in the original implementation where the training is on single categories: https://github.com/czq142857/implicit-decoder.

**Comment by WayneCV** [comment]
> This repo is designed to train a single model on 13 categories, so 128 resolution is probably too complex for the network to learn.
> 
> You can find 128 resolution in the original implementation where the training is on single categories: https://github.com/czq142857/implicit-decoder.

Thanks!
