### ISSUE TITLE
How to get the same visualizations (rendering) as the paper

### ISSUE THREAD

**Issue by WayneCV** [czq142857/IM-NET#26]
Hi, how to get the same rendering results as this image?  Thanks in advance! 
![image](https://github.com/czq142857/IM-NET/assets/119909226/ee2f11fe-b924-45f4-bce1-7ab35be1697d)

**Comment by czq142857** [comment]
Try blender https://www.blender.org/

**Comment by WayneCV** [comment]
> Try blender https://www.blender.org/

I solved, thanks!
