### ISSUE TITLE
Issue regarding PyMCubes

### ISSUE THREAD

**Issue by bharadwajdhornala** [czq142857/IM-NET#3]
Hi @czq142857 Thanks for your work. I am trying to generate outputs using IM-NET. I am stuck with PyMCubes. I have tried installing PyMCubes using pip install PyMCubes. It doesn't work. Is there any other way to install it. Thanks!!

**Comment by czq142857** [comment]
Please check whether you have successfully installed PyMCubes. If you type "import mcubes", what happens?
If you failed to install via pip, you can download the source code and run "python setup.py install".

**Comment by bharadwajdhornala** [comment]
Hi, thanks for fast reply. I have tried running via pip it didn't work. I have downloaded the source code and ran "python setup.py install". It gave this output
C:\Users\dhornala.bharadwaj\Downloads\IM-NET\IM-NET\IMGAN\PyMCubes>python setup.py install
running install
Compiling mcubes/src/_mcubes.pyx because it changed.
[1/1] Cythonizing mcubes/src/_mcubes.pyx
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\IM_NET\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\dhornala.bharadwaj\Downloads\IM-NET\IM-NET\IMGAN\PyMCubes\mcubes\src\_mcubes.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running bdist_egg
running egg_info
creating PyMCubes.egg-info
writing top-level names to PyMCubes.egg-info\top_level.txt
writing PyMCubes.egg-info\PKG-INFO
writing dependency_links to PyMCubes.egg-info\dependency_links.txt
writing manifest file 'PyMCubes.egg-info\SOURCES.txt'
reading manifest file 'PyMCubes.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'images\smoothing.png'
warning: no files found matching 'README.rst'
writing manifest file 'PyMCubes.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\mcubes
copying mcubes\exporter.py -> build\lib.win-amd64-3.5\mcubes
copying mcubes\numpy_smoothing.py -> build\lib.win-amd64-3.5\mcubes
copying mcubes\smoothing.py -> build\lib.win-amd64-3.5\mcubes
copying mcubes\__init__.py -> build\lib.win-amd64-3.5\mcubes
running build_ext
building 'mcubes._mcubes' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
Please guide.

**Comment by czq142857** [comment]
As indicated in the error message, you should download Microsoft Visual C++ 14.0. Please google on how to install it.

**Comment by bharadwajdhornala** [comment]
I have downloaded Microsoft Visual C++ 14.0. But still when I run the command it gives the same error. Is there any method to link MSVC to python?

**Comment by czq142857** [comment]
Sorry, I have not encountered this issue before, so I cannot really help you.
It looks like a generic issue that is not specific to this repo. Therefore please Google on the problem:
building python extension error: Microsoft Visual C++ 14.0 is required.
