### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by bharadwajdhornala** [czq142857/IM-NET#4]
Hi @czq142857 Thanks for the code. I have got any error while running the command from IMSVR **python main.py --train --epoch 200** . Error is 
self.data_points = (self.data_points_int.astype(np.float32)+0.5)/256-0.5
MemoryError: Unable to allocate 6.41 GiB for an array with shape (35019, 16384, 3) and data type float32
Please guide. Thanks!!

**Comment by czq142857** [comment]
It is an Out Of Memory (OOM) error. Try using a better machine.
Or you can modify the code to convert data points from integers (self.data_points_int) to float numbers in each mini-batch, instead of converting all of them as a preprocessing step (as written in the current code).
