### ISSUE TITLE
Optimize_mesh 

### ISSUE THREAD

**Issue by bharadwajdhornala** [czq142857/IM-NET#5]
Hi @czq142857  Thanks for the improved code in Tensorflow and PyTorch. With changes made in both the improved, how good is the improved code outputs according to you? Can you explain the use of  z2voxel and optimize_mesh?

**Comment by czq142857** [comment]
Please run the code to see the results.
Please read function "test" to understand how to use the two functions.
z2voxel: coarse-to-fine sampling for inference to speed up testing.
optimize_mesh: post-processing to make the output mesh smoother. To enable, find and uncomment all "self.optimize_mesh(vertices,model_z)".

Please read the README.md and the code before asking any questions next time.
