### ISSUE TITLE
Pretrained hdf5 file

### ISSUE THREAD

**Issue by bharadwajdhornala** [czq142857/IM-NET#6]
Hi @czq142857 Is there any part for preparation of all_vox256_img_z.hdf5. If yes, could you please guide me through it.

Thanks in advance.

**Comment by czq142857** [comment]
Please read the readme.md for details.
You need to train an AE first, then extract latent codes for SVR.
Those latent codes are saved in all_vox256_img_z.hdf5.
The command to extract latent codes is "python main.py --ae".

For naive questions like this, please email me directly. Do not post it on Github.
