### ISSUE TITLE
How to train this model on my custom mesh 3D model?

### ISSUE THREAD

**Issue by nitish11** [czq142857/IM-NET#8]
While checking the link for data preparation,
https://github.com/czq142857/IM-NET#datasets-and-pre-trained-weights

If I have 3D mesh models, what steps should I follow to convert the dataset to point-value pairs?

**Comment by czq142857** [comment]
Please check the data preparation code in the original implementation:
https://github.com/czq142857/implicit-decoder/tree/master/point_sampling

The generated data files are compatible for both the old and the latest implementations.

Best,
Zhiqin

**Comment by nitish11** [comment]
@czq142857  : Thanks for the instructions. I followed the steps and trained my own model. 
While using the trained model, I am getting all the dimensions of intermediate variables correctly. 
But, I am getting an error in [z2voxel code](https://github.com/czq142857/IM-NET/blob/master/IMSVR/model.py#L498), after this step, `model_float = self.z2voxel(model_z)`, 
model_float is coming as all zeros values. What could be the possible error?
